general {
    disable_loading_bar = true
    hide_cursor = true
    grace = 0
    no_fade_in = false
    no_fade_out = false
}

background {
    monitor =
    path = $HOME/.cache/current_wallpaper
    blur_passes = 0
    contrast = 1.0
    brightness = 0.65
    vibrancy = 1.0
    vibrancy_darkness = 0.0
}

image {
    monitor =
    path = /home/dousai/.dotfiles/config/theme/crt-overlay.png
    size = 1200
    rounding = 0
    border_size = 0
    halign = center
    valign = center
    zindex = 0
}

input-field {
    monitor =
    size = 280, 46
    outline_thickness = 1
    dots_size = 0.28
    dots_spacing = 0.35
    dots_center = true
    outer_color = rgba(244, 244, 244, 0.25)
    inner_color = rgba(10, 10, 10, 0.9)
    font_color = rgba(244, 244, 244, 1.0)
    font_family = DepartureMono Nerd Font Bold
    fade_on_empty = false
    placeholder_text = <span foreground="##f4f4f4aa">ENTER PASSWORD</span>
    hide_input = false
    rounding = 0
    check_color = rgba(244, 244, 244, 0.25)
    fail_color = rgba(199, 62, 62, 1.0)
    fail_text = <span foreground="##c73e3e">ACCESS DENIED</span>
    fail_timeout = 2000
    capslock_color = rgba(255, 180, 84, 1.0)
    position = 0, 0
    halign = center
    valign = center
}
