#################
### AUTOSTART ###
#################

exec-once = hyprlock
exec-once = blueman-applet
exec-once = hyprpaper
exec-once = waybar
exec-once = swaync
exec-once = wl-paste --watch cliphist store
exec-once = hyprctl setcursor Bibata-Modern-Ice 24
