##############################
### WINDOWS AND WORKSPACES ###
##############################

# Window rules
windowrule = border_size 2, match:float true
windowrule = border_color rgba(ffffffff) rgba(ffffffff), match:float true

# Workspace assignments
workspace = 1, monitor:eDP-1, default:true
workspace = 2, monitor:eDP-1
workspace = 3, monitor:eDP-1
workspace = 4, monitor:DP-2, default:true, persistent:false
