hl.on("hyprland.start", function()
	hl.exec_cmd("hyprlock")
	hl.exec_cmd("blueman-applet")
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("waybar")
	hl.exec_cmd("swaync")
	hl.exec_cmd("sh -c 'sleep 1 && swaync-client -dn'")
	hl.exec_cmd("wl-paste --watch cliphist store")
	hl.exec_cmd("hyprctl setcursor Bibata-Modern-Ice 24")
	hl.exec_cmd("~/.config/waybar/script/notify-listener.sh")
end)
